# (from: https://github.com/codecov/example-node/blob/master/.travis.yml)
language: node_js
sudo: false
node_js:
  - "12"
  - "10"
  - "8"
install:
  - npm install
script:
  - npm test
  # Test example
  - npm run build && cd example && npm i && npm run examples
